version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:13
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - ./dockerConfig/postgres-dev-init.sql:/docker-entrypoint-initdb.d/init.sql # will setup dev database woa for me
      - ./database/migrations:/home/node/app/database/migrations
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

#  pycount-backend:
#    image: pycount-backend:dev
#    container_name: pycount-backend
#    restart: always
#    depends_on:
#      - postgres
#    build:
#      context: .
#      target: dependencies
#    ports:
#      - ${PORT}:${PORT}
#      - 9229:9229
#    env_file:
#      - .env
#    environment:
#      - PG_HOST=postgres
#      - REDIS_HOST=redis
#    volumes:
#      - ./:/home/node/app
#    command: dumb-init node ace serve --watch --node-args="--inspect=0.0.0.0"

volumes:
  postgres_volume:
