apiVersion: apps/v1
kind: Deployment
metadata:
  name: pycount-backend-deploy
  namespace: pycount
spec:
  selector:
    matchLabels:
      app: pycount-backend
  template:
    metadata:
      labels:
        app: pycount-backend
    spec:
      containers:
        - name: pycount-backend-deploy
          image: duratm/pycount-backend:dev
          imagePullPolicy: "Always"
          ports:
            - containerPort: 3333
          envFrom:
            - configMapRef:
                name: pycount-database-conf
          # Ativar apenas apos configuracao da base de dados
          lifecycle:
            postStart:
              exec:
                # Lance la migration
                command:
                  [
                    "/bin/sh",
                    "-c",
                    "node ace migration:run --force",
                  ]
