apiVersion: apps/v1
kind: Deployment
metadata:
  name: pycount-backend-deploy
  namespace: pycount
spec:
  selector:
    matchLabels:
      app: pycount-backend
  template:
    metadata:
      labels:
        app: pycount-backend
    spec:
      containers:
        - name: pycount-backend-deploy
          image: duratm/pycount-backend:1.1.0-alpha.1
          imagePullPolicy: "Always"
          ports:
            - containerPort: 3333
          envFrom:
            - configMapRef:
                name: pycount-database-conf
