apiVersion: v1
kind: PersistentVolumeClaim # Create PVC
metadata:
  name: pycount-database-pvc # Sets name of PV
  namespace: pycount
  labels:
      app: pycount-database
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce # Sets read and write access
  resources:
    requests:
      storage: 10Gi # Sets volume size
