apiVersion: v1
kind: Service
metadata:
  name: pycount-database-svc # Sets service name
  namespace: pycount
  labels:
    app: pycount-database # Labels and Selectors
spec:
  type: NodePort # Sets service type
  selector:
    app: pycount-database
  ports:
    - name: postgres # Sets port name
      protocol: TCP
      targetPort: 5432 # Sets target port
      nodePort: 30000 # Sets node port
      port: 5432 # Sets port to run the postgres application

