apiVersion: v1
kind: PersistentVolume # Create a PV
metadata:
  name: pycount-minio-pv # Sets PV's name
  namespace: pycount
  labels:
    app: pycount-minio
    type: local # Sets PV's type to local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi # Sets PV Volume
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/volume" # Sets the volume's path
